
import type { Metadata } from "next";
import AboutMe from './about/page';


  export const metadata: Metadata = {
    title: "Jorge's Portfolio",
    description: "Generated by create next app",
    viewport: "width=device-width, initial-scale=1",
  };
export default function Home() {


  return (
 
      <div className="mt-auto">
        <AboutMe />
      </div>

  );
}
