
import type { Metadata } from "next";
import {AboutMe} from './about/page';


  export const metadata: Metadata = {
    title: "Jorge's Portfolio",
    description: "Generated by create next app",
  };
export default function Home() {


  return (
 
      <div>
        <AboutMe />
      </div>

  );
}
